Avoid encoding urls if they are already encoded
everypolitician-scrapers/macedonia-sobranie pull request #1
Opened 2016-09-30 15:29 UTC by octopusinvitro

As [this issue](https://github.com/everypolitician/everypolitician-data/issues/12584) states, we were applying encoding to the urls of the politicians no matter if they were already encoded or not, resulting in some image urls being encoded twice.

This change checks first if the image is not encoded before encoding it.

Closes https://github.com/everypolitician/everypolitician-data/issues/12584

2016-09-30 18:00 UTC, tmtmtmtm requested changes
Wouldn't a simpler approach be to unescape the image first before escaping it? i.e. 

``` ruby
URI.escape(URI.unescape(data[:image]))
```

2016-10-04 14:00 UTC, octopusinvitro commented
@tmtmtmtm Feedback addressed.

The reason what I had not just unescaped and then escaped all urls is because I didn't want to introduce bugs in the code by mutating urls that in principle are ok. I wanted to only touch the urls that were broken and leave the others untouched.

2016-10-09 07:30 UTC, tmtmtmtm commented
>  didn't want to introduce bugs in the code by mutating urls that in principle are ok

What bugs might this introduce? What are the circumstances in which unescaping and then escaping would change URLs, other than those ones which were already the subject of this change?

2017-02-05 16:04 UTC, tmtmtmtm commented
superseded by #3

2017-02-05 16:04 UTC, closed without merging